export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAIL = 'FETCH_TODOS_FAIL';
export const VIEWED_QUERY_REQUEST = 'VIEWED_QUERY_REQUEST';
export const VIEWED_QUERY_SUCCESS = 'VIEWED_QUERY_SUCCESS';
export const VIEWED_QUERY_FAIL = 'VIEWED_QUERY_FAIL';
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';
export const COMPLETE_TODO_REQUEST = 'COMPLETE_TODO_REQUST';
export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';
export const COMPLETE_TODO_FAIL = 'COMPLETE_TODO_FAIL';

// Modal
export const OPEN_MODAL_REQUEST = 'OPEN_MODAL_REQUEST';
export const OPEN_MODAL_SUCCESS = 'OPEN_MODAL_SUCCESS';
export const OPEN_MODAL_FAIL = 'OPEN_MODAL_FAIL';
export const CLOSE_MODAL_REQUEST = 'CLOSE_MODAL_REQUEST';
export const CLOSE_MODAL_SUCCESS = 'CLOSE_MODAL_SUCCESS';
export const CLOSE_MODAL_FAIL = 'CLOSE_MODAL_FAIL';
